blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Obednal97/profolio/discussions
    about: Ask questions, get help, and discuss ideas with the community
  - name: 🔒 Security Vulnerability Report
    url: https://github.com/Obednal97/profolio/security/advisories/new
    about: Report security vulnerabilities privately and responsibly
  - name: 📚 Documentation
    url: https://github.com/Obednal97/profolio#readme
    about: Check our comprehensive documentation and installation guides
  - name: 🚀 Installation Help
    url: https://github.com/Obednal97/profolio/discussions/categories/q-a
    about: Get help with installation, configuration, and troubleshooting 